# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# 実行結果の前後に余白をつけない
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

#コマンドのタイムアウト時間対策
command_timeout = 1000

#Pastel Powerline Preset
format = """
[┌](bold #65dcfc)[](#133A8F)\
$username\
[](bg:#236cf1 fg:#133A8F)\
$directory\
[](fg:#236cf1 bg:#5483E7)\
$git_branch\
$git_status\
[](fg:#5483E7 bg:#81A3ED)\
$python\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#81A3ED bg:#AAC1F2)\
$docker_context\
[](fg:#AAC1F2 bg:#33658A)\
$time\
[ ](fg:#33658A)
[└─>](bold #65dcfc) """

[username]
show_always = true
style_user = "bg:#133A8F"
style_root = "bg:#133A8F"
format = "[$user🦡]($style)"

    
[battery]
# disabled = true
# full_symbol = ""
# charging_symbol = " "
# discharging_symbol = " "
# unknown_symbol = ""
# empty_symbol = ""
# format = "[[](bg:#DE935F fg:#A6A6A6)$symbol$percentage[](bg:#A6A6A6 fg:#DE935F)]($style)"
# [[battery.display]]
# threshold = 10
# style = "bold bg:#DE935F fg:#EEEEEE"
# [[battery.display]]
# threshold = 20
# style = "bg:#DE935F fg:#111111"
#     
# # [battery]
# full_symbol  = "🔋"
# charging_symbol  = "⚡️"
# discharging_symbol  = "💀"

[directory]
style = "bg:#236cf1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = ""

[directory.substitutions]
"~/Documents" = ""
"~/Music" = ""
"~/Movies" = ""
"~/Pictures" = ""
"~/Sources" = ""

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"
format = "$symbol "

[git_branch]
# disabled = true
symbol = " "
# symbol = " " # alternate
style = "bg:#96ab5f fg:#111111"
# truncation_length = 4
# truncation_symbol = ""
format = "[[](bg:#96ab5f fg:#A6A6A6)$symbol$branch[](bg:#A6A6A6 fg:#96ab5f)]($style)"

[git_commit]
# disabled = true
style = "bg:#E58F73 fg:#111111"
commit_hash_length = 4
# only_detached = true
format = "[[](bg:#E58F73 fg:#A6A6A6)#$hash[](bg:#A6A6A6 fg:#E58F73)]($style)"

[git_state]
# disabled = true
style = "bg:#E0B25D fg:111111"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '\([[](bg:#E0B25D fg:#A6A6A6)$state($progress_current/$progress_total)[](bg:#A6A6A6 fg:#E0B25D)]($style)\)'

[git_status]
# disabled = true
style = "bg:#E0B25D fg:#000000"
stashed = " ${count}"
ahead = "⇡ $count "
behind = "⇣ $count "
diverged = "李 ${ahead_count} ${behind_count}"
conflicted = "⚔️${count}"
deleted = " ${count}"
renamed = "﫦${count}"
modified = " 📝${count}"
staged = "  ${count}"
untracked = " 🤷 ${count}"
format = "([[](bg:#E0B25D fg:#A6A6A6)$stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind[](bg:#A6A6A6 fg:#E0B25D)]($style))"

[python]
# disabled = true
symbol = " "
style = "bg:#EBD45B fg:#111111"
pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[[](bg:#EBD45B fg:#A6A6A6)$symbol$pyenv_prefix$version(\($virtualenv\))[](bg:#A6A6A6 fg:#EBD45B)]($style)'

[jobs]
symbol  = "+ "
threshold = 4

[memory_usage]
disabled = true
threshold = -1
symbol  = " "
style = "bold dimmed green"

[hg_branch]
format = "on [🌱 $branch](bold purple)"
truncation_length = 4
truncation_symbol = ""

[nodejs]
format = "via [🤖 $version](bold green) "

[package]
format = "via [🎁 $version](208 bold) "

[php]
format = "via [🔹 $version](147 bold) "

[perl]
format = "via [🐪 $version]($style) "

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[time]
disabled = false
style = "bg:#33658A"
format = '[🕙\[$time\]]($style)'
time_format = "%T"
utc_time_offset = "+9"
time_range = "4:00:00-21:00:00"

[hostname]
ssh_only = false
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false

[dotnet]
symbol = "🥅 "
style = "green"
heuristic = false

[custom.direnv]
command = "cat .envrc | grep -v -E '^[ ]*#|^$' | wc -l"
style = "bg:white fg:black"
format = "[direnv \\($output\\)]($style) "